### ISSUE TITLE
Support  websocket

### ISSUE THREAD

**Issue by kotbegemot** [vinniefalco/beast2#1]
Will the new version of the library have support for a websocket ?

**Comment by vinniefalco** [comment]
Eventually yes but the current Boost.Beast will be the official "websocket solution" for several more years. Also note that this "beast2" is pretty much dead. I do not plan to do a "Beast 2.0", so I should probably archive this repository. Instead, I am building a completely new HTTP protocol and networking library from scratch, making different foundational design choices from Beast. This will not be backward-compatible with Beast and will instead be a new offering with additional features, with the same low-level approach.

Eventually I will build a replacement websocket library using these new design principles but for now the focus is on HTTP. You can see these new libraries here (note, they are still in development)

https://github.com/vinniefalco/http_proto/
https://github.com/vinniefalco/http_io

However, these libraries are on pause while I finish Boost.URL:

https://github.com/CPPAlliance/url

Boost.URL is in a highly-usable state but still has some work left and it needs to go through the Boost review process.
